'use client';
import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'es' | 'en';

const translations = {
  es: {
    'nav.home': 'Inicio', 'nav.about': 'Nosotros', 'nav.catalog': 'Catálogo',
    'nav.quality': 'Calidad', 'nav.infra': 'Infraestructura', 'nav.contact': 'Contacto',
    'nav.cta': 'Cotizar Ahora',
    'hero.tag': '🇵🇪 Empresa 100% Peruana · 20+ Años de Experiencia',
    'hero.h1a': 'Perú Frost:', 'hero.h1b': 'Tradición', 'hero.h1c': 'transformada en',
    'hero.h1d': 'excelencia',
    'hero.sub': 'Procesamos y exportamos productos hidrobiológicos congelados con los más altos estándares de calidad, inocuidad y sostenibilidad hacia más de',
    'hero.countries': '56 países', 'hero.btn1': 'Ver Catálogo', 'hero.btn2': 'Cotizar Ahora',
    'hero.scroll': 'Descubrir',
    'news.tag': 'Noticias & Actualidad', 'news.h2': 'Últimas Novedades',
    'stats.years': 'Años de experiencia', 'stats.years.sub': 'En la industria pesquera',
    'stats.countries': 'Países de destino', 'stats.countries.sub': 'Exportación global',
    'stats.capacity': 'Capacidad frigorífica', 'stats.capacity.sub': 'Almacenamiento a -25°C',
    'stats.clients': 'Clientes globales', 'stats.clients.sub': 'En todo el mundo',
    'quality.tag': 'Trazabilidad Total', 'quality.h2a': 'Exigimos los mismos',
    'quality.h2b': 'estándares', 'quality.h2c': 'que ofrecemos',
    'quality.body': 'Exigimos a nuestros proveedores los mismos permisos de calidad y trazabilidad que ofrecemos a nuestros clientes. Cada producto tiene historia verificable desde la captura hasta el contenedor.',
    'quality.btn': 'Ver Certificaciones',
    'cold.tag': 'Cadena de Frío', 'cold.h2a': 'Temperatura garantizada',
    'cold.body': 'Mantenemos la cadena de frío sin interrupción desde la captura hasta la entrega, garantizando la máxima inocuidad y calidad organoléptica.',
    'products.tag': 'Portafolio de Productos', 'products.h2a': 'Productos a',
    'products.h2b': 'su medida',
    'products.body': 'Tamaños, cortes y especificaciones exactas según sus requerimientos. Producimos bajo los estándares internacionales de los mercados más exigentes.',
    'products.sheet': 'Ficha técnica completa', 'products.all': 'Ver Catálogo Completo',
    'globe.tag': 'Red de Exportación Global', 'globe.h3a': 'Llevamos Perú al',
    'globe.h3b': 'mundo entero',
    'globe.body': 'Desde nuestra planta en Paita, Piura, exportamos productos de alta calidad a más de',
    'globe.countries': '56 países', 'globe.in': 'en todos los continentes.',
    'globe.click': '↑ Haz clic en una región del mapa o en las tarjetas para ver los países de destino',
    'globe.active': 'Mercado de destino activo',
    'certs.tag': 'Aval Internacional', 'certs.h2a': 'Certificaciones que',
    'certs.h2b': 'garantizan', 'certs.h2c': 'la calidad',
    'certs.btn': 'Ver detalle de certificaciones',
    'cta.tag': 'Personalización Total', 'cta.h2': 'Productos a su medida',
    'cta.body': 'Tamaños, cortes y especificaciones exactas según sus requerimientos. Trabajamos con usted para garantizar que cada lote cumpla exactamente con lo que su mercado demanda.',
    'cta.btn1': 'Solicitar Cotización', 'cta.btn2': 'Ver Infraestructura',
    'footer.desc': 'Empresa 100% peruana con más de 20 años protegiendo la inversión de nuestros clientes en la industria pesquera global.',
    'footer.nav': 'Navegación', 'footer.legal': 'Legal & Ética', 'footer.contact': 'Contacto',
    'footer.email.label': 'Email Comercial', 'footer.phone.label': 'Teléfono',
    'footer.lima.label': 'Oficina Lima', 'footer.paita.label': 'Planta Paita',
    'footer.copy': '© 2026 Perú Frost S.A.C. — RUC 20607856517. Todos los derechos reservados.',
    'footer.cert': 'Planta certificada',
    'footer.aa': 'GRADO AA',
    'regions.northAmerica': 'Norteamérica', 'regions.southAmerica': 'Sudamérica', 'regions.europe': 'Europa', 'regions.asia': 'Asia', 'regions.africa': 'África', 'regions.oceania': 'Oceanía',
    'partners.tag': 'Nuestras Alianzas',
    'partners.h2': 'Socios Estratégicos',
    'catalogo.hero.tag': 'Catálogo Oficial 2026',
    'catalogo.hero.title': 'Portafolio',
    'catalogo.hero.title.accent': 'Marino',
    'catalogo.hero.body': '+35 productos certificados BRCGS, HACCP y SMETA. Procesados en Paita, Perú para los mercados más exigentes del mundo.',
    'catalogo.star': 'Producto Estrella',
    'catalogo.tabs.pota': 'Calamar Gigante',
    'catalogo.tabs.peces': 'Peces',
    'catalogo.tabs.mariscos': 'Mariscos',
    'catalogo.tabs.principal': 'Productos Principales',
    'catalogo.tabs.subproducto': 'Subproductos',
    'catalogo.tabs.valor_agregado': 'Valor Agregado',
    'catalogo.pota.title': 'Calamar Gigante',
    'catalogo.pota.subtitle': 'Pota del Pacífico',
    'catalogo.pota.body': 'Capturada en las aguas peruanas. El calamar más grande del Pacífico sur. Procesado bajo estricta cadena de frío en nuestra planta certificada BRCGS AA en Paita.',
    'catalogo.pota.cuts': '+20 cortes',
    'catalogo.peces.tag': 'Especies Pelágicas y Demersales',
    'catalogo.peces.h2': 'Peces del Pacífico Sur',
    'catalogo.peces.body': 'Captura sostenible certificada. 8 especies de alta valorización para los mercados más exigentes.',
    'catalogo.mariscos.tag': 'Mariscos & Cefalópodos',
    'catalogo.mariscos.h2': 'Mariscos Selectos',
    'catalogo.mariscos.body': 'Desde el langostino artesanal hasta la concha de abanico de acuicultura certificada. La élite del mar peruano.',
    'catalogo.formats': 'Formatos de exportación',
    'catalogo.spec_sheet': 'Ver Ficha Técnica',
    'catalogo.coming': 'Próximamente',
    'catalogo.cta.tag': '¿Listo para cotizar?',
    'catalogo.cta.h2': 'Solicita tu cotización en menos de 24h',
    'catalogo.cta.body': 'Compártenos las especificaciones de volumen, empaque y destino y nuestro equipo comercial te responderá con una propuesta detallada.',
    'catalogo.cta.btn': 'Solicitar Cotización',
    'calidad.hero.tag': 'Sistema de Calidad Total',
    'calidad.hero.h1': 'Calidad que',
    'calidad.hero.h1.accent': 'inspira confianza',
    'calidad.hero.body': 'Nuestro sistema integrado garantiza que cada producto que exportamos cumple con las normativas más exigentes del mundo.',
    'calidad.certs.tag': 'Aval Internacional',
    'calidad.certs.h2': 'Certificaciones',
    'calidad.certs.h2.accent': 'globales',
    'calidad.certs.body': 'Haz clic en cada certificación para ver su alcance y los mercados que habilita.',
    'calidad.haccp.h2': 'Análisis de Peligros y',
    'calidad.haccp.h2.accent': 'Puntos Críticos de Control',
    'calidad.lab.tag': 'Control de Laboratorio',
    'calidad.lab.h2': 'Análisis en',
    'calidad.lab.h2.accent': 'cada lote',
    'calidad.bpm.tag': 'BPM y POES',
    'calidad.bpm.h2': 'Buenas Prácticas de',
    'calidad.bpm.h2.accent': 'Manufactura',
    'calidad.bpm.body': 'Cumplimiento estricto de las Buenas Prácticas de Manufactura (BPM) y Procedimientos Operacionales Estandarizados de Saneamiento (POES) en todas las áreas de nuestra planta.',
    'calidad.tech.tag': 'Tecnología',
    'calidad.tech.h2': 'Precisión',
    'calidad.tech.h2.accent': 'Automatizada',
    'calidad.tech.body': 'Nuestras líneas de procesamiento JBT Marel de última generación aseguran una precisión milimétrica en el corte y una eficiencia operativa que minimiza la manipulación manual, garantizando la máxima inocuidad.',
    'calidad.tech.traceable': 'Trazable',
    'calidad.tech.contamination': 'Contaminación',
    'calidad.doc.h2': '¿Necesita documentación técnica?',
    'calidad.doc.body': 'Nuestro equipo puede proveer fichas técnicas, certificados y especificaciones para cada producto según los requisitos de su mercado.',
    'calidad.doc.btn': 'Solicitar documentación',
    'infra.hero.tag': 'Planta Paita - Piura',
    'infra.hero.h1': 'Infraestructura de',
    'infra.hero.h1.accent': 'clase mundial',
    'infra.hero.body': 'Nuestra planta en la Zona Industrial de Paita combina tecnología de última generación con procesos certificados para garantizar la máxima inocuidad y eficiencia productiva.',
    'infra.gallery.tag': 'Galería de Instalaciones',
    'infra.gallery.h2': 'Infraestructura de',
    'infra.gallery.h2.accent': 'clase mundial',
    'infra.tech.tag': 'Tecnología',
    'infra.tech.h2': 'Equipamiento de',
    'infra.tech.h2.accent': 'vanguardia',
    'infra.fleet.tag': 'Nuestra Flota',
    'infra.fleet.h2': 'Embarcaciones propias para una',
    'infra.fleet.h2.accent': 'pesca sostenible',
    'infra.fleet.body': 'Operamos con tres embarcaciones exclusivamente dedicadas a la pesca de merluza, asegurando así el cumplimiento del 11% de la cuota nacional en Perú.',
    'infra.fleet.tech.title': 'Tecnología de Preservación',
    'infra.fleet.tech.body': 'Nuestras bodegas de barcos están equipadas con sistemas innovadores de agua de mar refrigerada para mantener la frescura durante todo el viaje. Este método preservativo es completamente natural, sin químicos, asegurando la calidad y protegiendo el ecosistema.',
    'infra.fleet.stats.title': '3 Embarcaciones Industriales',
    'infra.fleet.stats.sub': '11% de la cuota de Merluza Peruana',
    'infra.map.tag': 'Logística Integral',
    'infra.map.h2': 'Encuéntranos en',
    'infra.map.h2.accent': 'Paita, Piura',
    'infra.map.btn': 'Ver en Google Maps',
    'infra.cta.h2': '¿Le gustaría visitar nuestras instalaciones?',
    'infra.cta.body': 'Estamos listos para recibir a importadores y auditores internacionales en nuestra planta de Paita. Coordine su visita con nuestro equipo comercial.',
    'infra.cta.btn': 'Coordinar visita',
  },
  en: {
    'nav.home': 'Home', 'nav.about': 'About Us', 'nav.catalog': 'Catalog',
    'nav.quality': 'Quality', 'nav.infra': 'Infrastructure', 'nav.contact': 'Contact',
    'nav.cta': 'Get a Quote',
    'hero.tag': '🇵🇪 100% Peruvian Company · 20+ Years of Experience',
    'hero.h1a': 'Perú Frost:', 'hero.h1b': 'Tradition', 'hero.h1c': 'transformed into',
    'hero.h1d': 'excellence',
    'hero.sub': 'We process and export frozen fishery products with the highest standards of quality, food safety and sustainability to more than',
    'hero.countries': '56 countries', 'hero.btn1': 'View Catalog', 'hero.btn2': 'Get a Quote',
    'hero.scroll': 'Discover',
    'news.tag': 'News & Updates', 'news.h2': 'Latest News',
    'stats.years': 'Years of experience', 'stats.years.sub': 'In the fishing industry',
    'stats.countries': 'Destination countries', 'stats.countries.sub': 'Global exports',
    'stats.capacity': 'Cold storage capacity', 'stats.capacity.sub': 'Storage at -25°C',
    'stats.clients': 'Global clients', 'stats.clients.sub': 'Around the world',
    'quality.tag': 'Full Traceability', 'quality.h2a': 'We demand the same',
    'quality.h2b': 'standards', 'quality.h2c': 'we deliver',
    'quality.body': 'We require our suppliers to meet the same quality and traceability standards we offer our clients. Every product leaving our Paita plant has a verifiable history from catch to container.',
    'quality.btn': 'View Certifications',
    'cold.tag': 'Cold Chain', 'cold.h2a': 'Guaranteed temperature',
    'cold.body': 'We maintain an uninterrupted cold chain from catch to delivery, ensuring maximum food safety and organoleptic quality.',
    'products.tag': 'Product Portfolio', 'products.h2a': 'Products',
    'products.h2b': 'tailored to you',
    'products.body': 'Exact sizes, cuts and specifications per your requirements. We produce under the international standards of the most demanding markets.',
    'products.sheet': 'Full technical sheet', 'products.all': 'View Full Catalog',
    'globe.tag': 'Global Export Network', 'globe.h3a': 'We bring Peru to',
    'globe.h3b': 'the world',
    'globe.body': 'From our plant in Paita, Piura, we export high-quality products to more than',
    'globe.countries': '56 countries', 'globe.in': 'across all continents.',
    'globe.click': '↑ Click on a region or the cards to see destination countries',
    'globe.active': 'Active destination market',
    'certs.tag': 'International Endorsement', 'certs.h2a': 'Certifications that',
    'certs.h2b': 'guarantee', 'certs.h2c': 'quality',
    'certs.btn': 'View certification details',
    'cta.tag': 'Full Customization', 'cta.h2': 'Products tailored to your needs',
    'cta.body': 'Exact sizes, cuts and specifications per your requirements. We work with you to ensure every batch meets exactly what your market demands.',
    'cta.btn1': 'Request a Quote', 'cta.btn2': 'View Infrastructure',
    'footer.desc': '100% Peruvian company with over 20 years protecting our clients\' investments in the global fishing industry.',
    'footer.nav': 'Navigation', 'footer.legal': 'Legal & Ethics', 'footer.contact': 'Contact',
    'footer.email.label': 'Commercial Email', 'footer.phone.label': 'Phone',
    'footer.lima.label': 'Lima Office', 'footer.paita.label': 'Paita Plant',
    'footer.copy': '© 2026 Perú Frost S.A.C. — RUC 20607856517. All rights reserved.',
    'footer.cert': 'Certified plant',
    'footer.aa': 'GRADE AA',
    'regions.northAmerica': 'North America', 'regions.southAmerica': 'South America', 'regions.europe': 'Europe', 'regions.asia': 'Asia', 'regions.africa': 'Africa', 'regions.oceania': 'Oceania',
    'partners.tag': 'Our Alliances',
    'partners.h2': 'Strategic Partners',
    'catalogo.hero.tag': 'Official Catalog 2026',
    'catalogo.hero.title': 'Marine',
    'catalogo.hero.title.accent': 'Portfolio',
    'catalogo.hero.body': '+35 products certified BRCGS, HACCP and SMETA. Processed in Paita, Peru for the world\'s most demanding markets.',
    'catalogo.star': 'Star Product',
    'catalogo.tabs.pota': 'Giant Squid',
    'catalogo.tabs.peces': 'Fish',
    'catalogo.tabs.mariscos': 'Shellfish & Octopus',
    'catalogo.tabs.principal': 'Main Products',
    'catalogo.tabs.subproducto': 'By-Products',
    'catalogo.tabs.valor_agregado': 'Value Added',
    'catalogo.pota.title': 'Giant Squid',
    'catalogo.pota.subtitle': 'Pacific Giant Squid',
    'catalogo.pota.body': 'Caught in Peruvian waters. The largest squid in the South Pacific. Processed under a strict cold chain in our BRCGS AA certified plant in Paita.',
    'catalogo.pota.cuts': '+20 cuts',
    'catalogo.peces.tag': 'Pelagic & Demersal Species',
    'catalogo.peces.h2': 'South Pacific Fish',
    'catalogo.peces.body': 'Certified sustainable catch. 8 high-value species for the most demanding markets.',
    'catalogo.mariscos.tag': 'Shellfish & Cephalopods',
    'catalogo.mariscos.h2': 'Selected Shellfish',
    'catalogo.mariscos.body': 'From artisanal shrimp to certified aquaculture scallops. The elite of the Peruvian sea.',
    'catalogo.formats': 'Export formats',
    'catalogo.spec_sheet': 'View Spec Sheet',
    'catalogo.coming': 'Coming Soon',
    'catalogo.cta.tag': 'Ready to quote?',
    'catalogo.cta.h2': 'Request your quote in less than 24h',
    'catalogo.cta.body': 'Share your volume, packaging and destination specifications and our sales team will respond with a detailed proposal.',
    'catalogo.cta.btn': 'Request Quote',
    'calidad.hero.tag': 'Total Quality System',
    'calidad.hero.h1': 'Quality that',
    'calidad.hero.h1.accent': 'inspires confidence',
    'calidad.hero.body': 'Our integrated system ensures that every product we export complies with the most demanding regulations in the world.',
    'calidad.certs.tag': 'International Endorsement',
    'calidad.certs.h2': 'Global',
    'calidad.certs.h2.accent': 'certifications',
    'calidad.certs.body': 'Click on each certification to see its scope and the markets it enables.',
    'calidad.haccp.h2': 'Hazard Analysis and',
    'calidad.haccp.h2.accent': 'Critical Control Points',
    'calidad.lab.tag': 'Laboratory Control',
    'calidad.lab.h2': 'Analysis per',
    'calidad.lab.h2.accent': 'each batch',
    'calidad.bpm.tag': 'GMP & SSOP',
    'calidad.bpm.h2': 'Good Manufacturing',
    'calidad.bpm.h2.accent': 'Practices',
    'calidad.bpm.body': 'Strict compliance with Good Manufacturing Practices (GMP) and Sanitation Standard Operating Procedures (SSOP) in all areas of our plant.',
    'calidad.tech.tag': 'Technology',
    'calidad.tech.h2': 'Automated',
    'calidad.tech.h2.accent': 'Precision',
    'calidad.tech.body': 'Our state-of-the-art JBT Marel processing lines ensure millimeter precision in cutting and operational efficiency that minimizes manual handling, guaranteeing maximum safety.',
    'calidad.tech.traceable': 'Traceable',
    'calidad.tech.contamination': 'Contamination',
    'calidad.doc.h2': 'Need technical documentation?',
    'calidad.doc.body': 'Our team can provide technical data sheets, certificates and specifications for each product according to your market requirements.',
    'calidad.doc.btn': 'Request documentation',
    'infra.hero.tag': 'Paita Plant - Piura',
    'infra.hero.h1': 'World-class',
    'infra.hero.h1.accent': 'infrastructure',
    'infra.hero.body': 'Our plant in the Paita Industrial Zone combines latest-generation technology with certified processes to guarantee maximum safety and productive efficiency.',
    'infra.gallery.tag': 'Facility Gallery',
    'infra.gallery.h2': 'World-class',
    'infra.gallery.h2.accent': 'infrastructure',
    'infra.tech.tag': 'Technology',
    'infra.tech.h2': 'Modern',
    'infra.tech.h2.accent': 'Equipment',
    'infra.fleet.tag': 'Our Fleet',
    'infra.fleet.h2': 'Own vessels for a',
    'infra.fleet.h2.accent': 'sustainable fishing',
    'infra.fleet.body': 'We operate three vessels exclusively dedicated to hake fishing, ensuring compliance with 11% of the national quota in Peru.',
    'infra.fleet.tech.title': 'Preservation Technology',
    'infra.fleet.tech.body': 'Our ship holds are equipped with innovative refrigerated seawater systems to maintain freshness throughout the trip. This preservation method is completely natural, chemical-free, ensuring quality and protecting the ecosystem.',
    'infra.fleet.stats.title': '3 Industrial Vessels',
    'infra.fleet.stats.sub': '11% of the Peruvian Hake quota',
    'infra.map.tag': 'Integrated Logistics',
    'infra.map.h2': 'Find us in',
    'infra.map.h2.accent': 'Paita, Piura',
    'infra.map.btn': 'Open in Google Maps',
    'infra.cta.h2': 'Would you like to visit our facilities?',
    'infra.cta.body': 'We are ready to receive international importers and auditors at our Paita plant. Coordinate your visit with our sales team.',
    'infra.cta.btn': 'Coordinate visit',
  },
};

interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: (k: string) => string; }
const Ctx = createContext<LangCtx>({ lang: 'es', setLang: () => { }, t: (k) => k });

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('es');
  const t = (key: string): string => (translations[lang] as Record<string, string>)[key] || key;
  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export const useLang = () => useContext(Ctx);
